name: aws_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  buildruntest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # update the operating system
      - name: update OS
        run: sudo apt-get update

      # check working directory
      - name: check working directory
        run: pwd; ls

      # install AWSCLI
      - name: install awscli
        run: bin/install_aswcli.sh

      # figure out what system we are on
      - name: kernelquery
        run: uname -a

      # figure out what distro we are on
      - name: distroquery
        run: cat /etc/lsb-release
