name: aws_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  awstest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # update the operating system
      - name: update OS
        run: sudo apt-get update

      # install AWSCLI
      - name: install awscli
        run: ./bin/install_awscli.sh

      # configure AWSCLI
      - name: configure awscli
        run: ./bin/config_awscli.sh
        env:
          AWS_KEYPAIR: ${{secrets.GEORGES_AWS_KEYPAIR}}
	  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
	  AWS_ACCESS_KEY_SECRET: ${{secrets.AWS_ACCESS_KEY_SECRET}}

      # basic test of awscli
      - name: basic test
        run: /usr/local/bin/aws ec2 describe-instances

      # use AWS certificate to contact our VM
      - name: server uptime
        run: ssh -i ~/.ssh/aws.pem ubuntu@54.145.76.53 uptime
