name: aws_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  awstest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # update the operating system
      - name: update OS
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # install AWSCLI
      - name: install awscli
        run: ./bin/awscli_install.sh

      # configure AWSCLI
      - name: configure awscli
        run: ./bin/awscli_config.sh
        env:
          AWS_KEYPAIR: ${{secrets.GEORGES_AWS_KEYPAIR}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_ACCESS_KEY_SECRET: ${{secrets.AWS_ACCESS_KEY_SECRET}}

      # launch a VM and wait for start complete
      - name: basic test
        run: |
          . ./bin/awscli_launch.sh
          instanceid=$(launch)
          echo "instanceid=${instanceid}" >> ${GITHUB_ENV}
          wait_run ${instanceid}
          echo "ipaddr=$(get_ipaddr ${instanceid})" >> ${GITHUB_ENV}

      # use AWS certificate to contact our VM
      - name: server uptime
        run: ssh -i ~/.ssh/aws.pem ubuntu@${ipaddr} uptime

      # terminate the VM
      - name: finish
        run: |
          . ./bin/awscli_launch.sh
          terminate ${instanceid}
